name: Update posts
on:
  workflow_dispatch:
  schedule: 
  - cron: "0 3 * * *" 
jobs:
  update_readme:
   name: "update Readme"
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Update Devto
       uses: gautamkrishnar/blog-post-workflow@master
       with:
         feed_list: ${{ secrets.DEVTO_FEED }}
         comment_tag_name: DEVTO-POST-LIST
         commit_message: "Automatic update Dev.to posts list"
         max_post_count: 10
     - name: Update Strava
       uses: gautamkrishnar/blog-post-workflow@master
       with:
         feed_list: ${{ secrets.STRAVA_FEED }}
         comment_tag_name: STRAVA-POST-LIST
         commit_message: "Automatic update Strava activities list"
         max_post_count: 10
